"""Push/pull custom 3rd-party secrets to/from Coolify applications.

Magic Variables (``SERVICE_PASSWORD_*``) are generated by Coolify itself and
must never be pushed via this script. Only real 3rd-party secrets (e.g.
``OPENWEATHER_API_KEY``) go through here.

Source file is expected at ``~/.config/air-quality/secrets.env`` (gitignored
path, not sourced by ``.envrc`` — only read on explicit sync).

Usage:
    python -m infra.coolify.sync_secrets push --app aqi-streamlit
    python -m infra.coolify.sync_secrets push --file ~/.config/air-quality/secrets.env
    python -m infra.coolify.sync_secrets pull --app aqi-streamlit
    python -m infra.coolify.sync_secrets list
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

from infra.coolify.client import CoolifyClient, CoolifyError

logger = logging.getLogger(__name__)

DEFAULT_SECRETS_FILE = Path.home() / ".config" / "air-quality" / "secrets.env"

# Keys that Coolify owns — pushing these would fight Magic Variable generation.
MAGIC_PREFIXES = ("SERVICE_PASSWORD_", "SERVICE_USER_", "SERVICE_URL_", "SERVICE_FQDN_")


def parse_env_file(path: Path) -> dict[str, str]:
    """Parse a KEY=VALUE dotenv file (quotes stripped)."""
    result: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if not key:
            continue
        if key.startswith(MAGIC_PREFIXES):
            logger.warning("Skipping %s (Magic Variable — Coolify owns this value).", key)
            continue
        result[key] = value
    return result


def _find_app(client: CoolifyClient, name: str) -> dict:
    apps = client.list_applications()
    match = next((a for a in apps if a.get("name") == name), None)
    if not match:
        raise CoolifyError(f"Application '{name}' not found in Coolify.")
    return match


def push(
    client: CoolifyClient,
    app_name: str,
    secrets_path: Path,
    is_build_time: bool = False,
) -> None:
    """Push all non-magic secrets from file to the given Coolify app."""
    app = _find_app(client, app_name)
    secrets = parse_env_file(secrets_path)
    if not secrets:
        logger.warning("No secrets to push from %s.", secrets_path)
        return
    variables = [
        {
            "key": key,
            "value": value,
            "is_build_time": is_build_time,
            "is_literal": True,
        }
        for key, value in secrets.items()
    ]
    client.upsert_envs_bulk(app["uuid"], variables)
    print(f"[OK] Pushed {len(variables)} secret(s) to {app_name}: " f"{', '.join(sorted(secrets))}")


def pull(client: CoolifyClient, app_name: str, reveal: bool = False) -> None:
    """List env keys for an app. Values are masked unless --reveal is given."""
    app = _find_app(client, app_name)
    envs = client.get_app_envs(app["uuid"])
    print(f"\nEnv variables for {app_name}:")
    for item in sorted(envs, key=lambda e: e.get("key", "")):
        key = item.get("key", "<?>")
        value = item.get("value", "") if reveal else "***"
        marker = "[magic]" if key.startswith(MAGIC_PREFIXES) else ""
        print(f"  {key}={value} {marker}".rstrip())


def list_all(client: CoolifyClient) -> None:
    """Print env key inventory across all apps (values hidden)."""
    for app in client.list_applications():
        name = app.get("name")
        try:
            envs = client.get_app_envs(app["uuid"])
        except CoolifyError as exc:
            print(f"\n{name}: ERROR — {exc}")
            continue
        print(f"\n{name}:")
        for item in sorted(envs, key=lambda e: e.get("key", "")):
            key = item.get("key", "<?>")
            marker = "[magic]" if key.startswith(MAGIC_PREFIXES) else ""
            print(f"  - {key} {marker}".rstrip())


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Sync custom secrets with Coolify.")
    sub = parser.add_subparsers(dest="command", required=True)

    push_p = sub.add_parser("push", help="Push secrets from file to an app.")
    push_p.add_argument("--app", required=True)
    push_p.add_argument("--file", default=str(DEFAULT_SECRETS_FILE))
    push_p.add_argument("--build-time", action="store_true")

    pull_p = sub.add_parser("pull", help="List env keys for an app.")
    pull_p.add_argument("--app", required=True)
    pull_p.add_argument("--reveal", action="store_true")

    sub.add_parser("list", help="Inventory env keys across all apps.")

    args = parser.parse_args(argv)
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s %(message)s",
    )

    with CoolifyClient() as client:
        if args.command == "push":
            push(client, args.app, Path(args.file), is_build_time=args.build_time)
            return 0
        if args.command == "pull":
            pull(client, args.app, reveal=args.reveal)
            return 0
        if args.command == "list":
            list_all(client)
            return 0

    return 1


if __name__ == "__main__":
    sys.exit(main())
